import DeciNSSE.Semantics.Tree

/-! # Finite trees

Inductively generated trees embed into the path-based semantics. This embedding
defines the domain of finite-tree solutions of flat constraints.
-/

namespace DeciNSSE

/-- Finite trees generated by bottom, top and a binary covariant constructor. -/
inductive FTree where
  | bot
  | top
  | node (l r : FTree)
  deriving DecidableEq, Repr

namespace FTree

/-- Embed a finite tree into the path-based tree semantics. -/
def toTree : FTree → Tree
  | bot => Tree.bot
  | top => Tree.top
  | node l r => Tree.node l.toTree r.toTree

end FTree
end DeciNSSE
