import DeciNSSE.Constraints.Basic

/-! # Covariant constraint closure

Reflexivity, transitivity and constructor decomposition generate the variable
closure. Finite saturation computes this relation and the supported root labels.
-/

namespace DeciNSSE

variable {n k : ℕ}

/-- Inequalities generated by reflexivity, transitivity, and one decomposition
rule quantified over the child index: from `f(a) ≤ u`, `u ≤⋯≤ v` and
`v ≤ f(b)`, infer `a i ≤ b i`. -/
inductive Derives (ϕ : Constraint n k) : V k → V k → Prop where
  | refl (x : V k) : Derives ϕ x x
  | trans {x y z : V k} : Derives ϕ x y → Derives ϕ y z → Derives ϕ x z
  | decomp {a b : Fin n → V k} {u v : V k} (i : Fin n) :
      Lit.fLe a u ∈ ϕ → Derives ϕ u v → Lit.leF v b ∈ ϕ →
      Derives ϕ (a i) (b i)

/-- Every derived variable inequality holds in each covariant solution. -/
theorem Derives.sound {ϕ : Constraint n k} {x y : V k} (h : Derives ϕ x y) :
    ∀ ρ, Covariant.Sat ρ ϕ → ρ x ≤ ρ y := by
  induction h with
  | refl x => exact fun _ _ => le_rfl
  | trans _ _ ih₁ ih₂ => exact fun ρ hρ => le_trans (ih₁ ρ hρ) (ih₂ ρ hρ)
  | decomp i hl _ hu ih =>
    intro ρ hρ
    exact (Tree.node_le_node_iff ..).mp
      (le_trans (le_trans (hρ _ hl) (ih ρ hρ)) (hρ _ hu)) i

/-- A constructor lower bound reaches the variable through closure. -/
def LowerF (ϕ : Constraint n k) (x : V k) : Prop :=
  ∃ a u, Lit.fLe a u ∈ ϕ ∧ Derives ϕ u x

/-- A prescribed top reaches the variable through closure. -/
def LowerTop (ϕ : Constraint n k) (x : V k) : Prop :=
  ∃ u, Lit.eqTop u ∈ ϕ ∧ Derives ϕ u x

/-- Closure takes the variable to a constructor upper bound. -/
def UpperF (ϕ : Constraint n k) (x : V k) : Prop :=
  ∃ v b, Lit.leF v b ∈ ϕ ∧ Derives ϕ x v

/-- Closure takes the variable to a prescribed bottom. -/
def UpperBot (ϕ : Constraint n k) (x : V k) : Prop :=
  ∃ v, Lit.eqBot v ∈ ϕ ∧ Derives ϕ x v

theorem LowerF.sound {ϕ : Constraint n k} {x : V k} {ρ : V k → Tree n}
    (h : LowerF ϕ x) (hρ : Covariant.Sat ρ ϕ) : (ρ x).fn [] ≠ some Sym.bot := by
  obtain ⟨a, u, hl, hd⟩ := h
  intro hx
  have hle : Tree.node (ρ ∘ a) ≤ ρ x := le_trans (hρ _ hl) (hd.sound ρ hρ)
  rw [(Tree.root_eq_bot_iff _).mp hx] at hle
  exact Tree.node_ne_bot _ ((Tree.le_bot_iff _).mp hle)

theorem LowerTop.sound {ϕ : Constraint n k} {x : V k} {ρ : V k → Tree n}
    (h : LowerTop ϕ x) (hρ : Covariant.Sat ρ ϕ) : ρ x = Tree.top := by
  obtain ⟨u, hl, hd⟩ := h
  have hle := hd.sound ρ hρ
  have hu : ρ u = Tree.top := hρ _ hl
  rw [hu] at hle
  exact (Tree.top_le_iff _).mp hle

theorem UpperF.sound {ϕ : Constraint n k} {x : V k} {ρ : V k → Tree n}
    (h : UpperF ϕ x) (hρ : Covariant.Sat ρ ϕ) : (ρ x).fn [] ≠ some Sym.top := by
  obtain ⟨v, b, hu, hd⟩ := h
  intro hx
  have hle : ρ x ≤ Tree.node (ρ ∘ b) := le_trans (hd.sound ρ hρ) (hρ _ hu)
  rw [(Tree.root_eq_top_iff _).mp hx] at hle
  exact Tree.node_ne_top _ ((Tree.top_le_iff _).mp hle)

theorem UpperBot.sound {ϕ : Constraint n k} {x : V k} {ρ : V k → Tree n}
    (h : UpperBot ϕ x) (hρ : Covariant.Sat ρ ϕ) : ρ x = Tree.bot := by
  obtain ⟨v, hl, hd⟩ := h
  have hle := hd.sound ρ hρ
  have hv : ρ v = Tree.bot := hρ _ hl
  rw [hv] at hle
  exact (Tree.le_bot_iff _).mp hle

/-- The three root clashes: top/bottom, top/constructor, constructor/bottom. -/
def LabelClash (ϕ : Constraint n k) : Prop :=
  ∃ x, (LowerTop ϕ x ∧ UpperBot ϕ x) ∨
    (LowerTop ϕ x ∧ UpperF ϕ x) ∨ (LowerF ϕ x ∧ UpperBot ϕ x)

/-- A label clash excludes every covariant solution. -/
theorem LabelClash.unsatisfiable {ϕ : Constraint n k} (h : LabelClash ϕ) :
    ¬ ∃ ρ, Covariant.Sat ρ ϕ := by
  rintro ⟨ρ, hρ⟩
  obtain ⟨x, (⟨hl, hu⟩ | ⟨hl, hu⟩ | ⟨hl, hu⟩)⟩ := h
  · exact Tree.top_ne_bot ((hl.sound hρ).symm.trans (hu.sound hρ))
  · exact hu.sound hρ (by rw [hl.sound hρ]; rfl)
  · exact hl.sound hρ (by rw [hu.sound hρ]; rfl)

namespace Lit

/-- Rename every variable of a flat literal. -/
def rename {m : ℕ} (r : V k → V m) : Lit n k → Lit n m
  | .leF x a => .leF (r x) (r ∘ a)
  | .fLe a x => .fLe (r ∘ a) (r x)
  | .eqBot x => .eqBot (r x)
  | .eqTop x => .eqTop (r x)

@[simp] theorem holds_rename {m : ℕ} (r : V k → V m) (ρ : V m → Tree n)
    (l : Lit n k) : Covariant.holds ρ (l.rename r) ↔ Covariant.holds (ρ ∘ r) l := by
  cases l <;> rfl

end Lit

theorem sat_rename {m : ℕ} (r : V k → V m) (ρ : V m → Tree n) (ϕ : Constraint n k) :
    Covariant.Sat ρ (ϕ.map (Lit.rename r)) ↔ Covariant.Sat (ρ ∘ r) ϕ := by
  simp [Covariant.Sat]

/-- Transport the closure along any renaming preserving literal membership. -/
theorem Derives.map {m : ℕ} {ϕ : Constraint n k} {ψ : Constraint n m} (r : V k → V m)
    (hr : ∀ l ∈ ϕ, l.rename r ∈ ψ) {a b : V k} (h : Derives ϕ a b) :
    Derives ψ (r a) (r b) := by
  induction h with
  | refl a => exact .refl _
  | trans _ _ ih ih' => exact .trans ih ih'
  | @decomp a b u v i hl _ hu ih =>
    exact Derives.decomp (a := r ∘ a) (b := r ∘ b) i (hr _ hl) ih (hr _ hu)

/-- The lower constructor literals `f(a) ≤ u`, as pairs `(a, u)`. -/
def lowerLits (ϕ : Constraint n k) : List ((Fin n → V k) × V k) :=
  ϕ.filterMap fun
    | .fLe a u => some (a, u)
    | _ => none

/-- The upper constructor literals `v ≤ f(b)`, as pairs `(v, b)`. -/
def upperLits (ϕ : Constraint n k) : List (V k × (Fin n → V k)) :=
  ϕ.filterMap fun
    | .leF v b => some (v, b)
    | _ => none

/-- The variables fixed to top. -/
def topVars (ϕ : Constraint n k) : List (V k) :=
  ϕ.filterMap fun
    | .eqTop u => some u
    | _ => none

/-- The variables fixed to bottom. -/
def botVars (ϕ : Constraint n k) : List (V k) :=
  ϕ.filterMap fun
    | .eqBot v => some v
    | _ => none

@[simp] theorem mem_lowerLits (ϕ : Constraint n k) (a : Fin n → V k) (u : V k) :
    (a, u) ∈ lowerLits ϕ ↔ Lit.fLe a u ∈ ϕ := by
  simp only [lowerLits, List.mem_filterMap]
  constructor
  · rintro ⟨l, hl, he⟩
    cases l <;> simp_all
  · intro h
    exact ⟨_, h, rfl⟩

@[simp] theorem mem_upperLits (ϕ : Constraint n k) (v : V k) (b : Fin n → V k) :
    (v, b) ∈ upperLits ϕ ↔ Lit.leF v b ∈ ϕ := by
  simp only [upperLits, List.mem_filterMap]
  constructor
  · rintro ⟨l, hl, he⟩
    cases l <;> simp_all
  · intro h
    exact ⟨_, h, rfl⟩

@[simp] theorem mem_topVars (ϕ : Constraint n k) (u : V k) :
    u ∈ topVars ϕ ↔ Lit.eqTop u ∈ ϕ := by
  simp only [topVars, List.mem_filterMap]
  constructor
  · rintro ⟨l, hl, he⟩
    cases l <;> simp_all
  · intro h
    exact ⟨_, h, rfl⟩

@[simp] theorem mem_botVars (ϕ : Constraint n k) (v : V k) :
    v ∈ botVars ϕ ↔ Lit.eqBot v ∈ ϕ := by
  simp only [botVars, List.mem_filterMap]
  constructor
  · rintro ⟨l, hl, he⟩
    cases l <;> simp_all
  · intro h
    exact ⟨_, h, rfl⟩

namespace Closure

/-- One decomposition step from the stored pairs, phrased over the literal lists
so that only list membership and the finite child index are searched. -/
def DecompStep (ϕ : Constraint n k) (s : Finset (V k × V k)) (x y : V k) : Prop :=
  ∃ l ∈ lowerLits ϕ, ∃ m ∈ upperLits ϕ, (l.2, m.1) ∈ s ∧ ∃ i, l.1 i = x ∧ m.2 i = y

instance (ϕ : Constraint n k) (s : Finset (V k × V k)) (x y : V k) :
    Decidable (DecompStep ϕ s x y) := by
  unfold DecompStep
  infer_instance

theorem decompStep_iff (ϕ : Constraint n k) (s : Finset (V k × V k)) (x y : V k) :
    DecompStep ϕ s x y ↔
      ∃ a u v b i, Lit.fLe a u ∈ ϕ ∧ (u, v) ∈ s ∧ Lit.leF v b ∈ ϕ ∧
        a i = x ∧ b i = y := by
  constructor
  · rintro ⟨⟨a, u⟩, hl, ⟨v, b⟩, hm, hs, i, hx, hy⟩
    exact ⟨a, u, v, b, i, (mem_lowerLits ϕ a u).mp hl, hs,
      (mem_upperLits ϕ v b).mp hm, hx, hy⟩
  · rintro ⟨a, u, v, b, i, hl, hs, hu, hx, hy⟩
    exact ⟨(a, u), (mem_lowerLits ϕ a u).mpr hl, (v, b), (mem_upperLits ϕ v b).mpr hu,
      hs, i, hx, hy⟩

/-- Retain known pairs and apply each closure rule once. All searches range
over finite variable sets, literal lists, and the finite child index. -/
def expand (ϕ : Constraint n k) (s : Finset (V k × V k)) : Finset (V k × V k) :=
  s ∪ Finset.univ.filter (fun p =>
    p.1 = p.2 ∨
    (∃ z, (p.1, z) ∈ s ∧ (z, p.2) ∈ s) ∨
    DecompStep ϕ s p.1 p.2)

theorem mem_expand (ϕ : Constraint n k) (s : Finset (V k × V k)) (x y : V k) :
    (x, y) ∈ expand ϕ s ↔
      (x, y) ∈ s ∨ x = y ∨
      (∃ z, (x, z) ∈ s ∧ (z, y) ∈ s) ∨
      (∃ a u v b i, Lit.fLe a u ∈ ϕ ∧ (u, v) ∈ s ∧ Lit.leF v b ∈ ϕ ∧
        a i = x ∧ b i = y) := by
  simp only [expand, Finset.mem_union, Finset.mem_filter, Finset.mem_univ, true_and,
    decompStep_iff]

theorem expand_sound (ϕ : Constraint n k) (s : Finset (V k × V k))
    (hs : ∀ p ∈ s, Derives ϕ p.1 p.2) :
    ∀ p ∈ expand ϕ s, Derives ϕ p.1 p.2 := by
  rintro ⟨x, y⟩ hp
  rcases (mem_expand ϕ s x y).mp hp with
    hp | rfl | ⟨z, hxz, hzy⟩ | ⟨a, u, v, b, i, hl, huv, hu, rfl, rfl⟩
  · exact hs _ hp
  · exact Derives.refl x
  · exact Derives.trans (hs (x, z) hxz) (hs (z, y) hzy)
  · exact Derives.decomp i hl (hs _ huv) hu

/-- Saturate the finite set of pairs. A recursive call strictly increases its
cardinality, so there can be at most `k * k` strict expansions. -/
def close (ϕ : Constraint n k) (s : Finset (V k × V k)) : Finset (V k × V k) :=
  if expand ϕ s ⊆ s then s else close ϕ (expand ϕ s)
termination_by k * k - s.card
decreasing_by
  have hs : s ⊂ expand ϕ s :=
    lt_of_le_not_ge Finset.subset_union_left (by assumption)
  have hlt := Finset.card_lt_card hs
  have hle := Finset.card_le_univ (s := expand ϕ s)
  simp only [Fintype.card_prod, Fintype.card_fin] at hle
  omega

/-- Saturation contains its input, is closed under all rules, and preserves
the invariant that every stored pair is derivable. -/
theorem close_spec (ϕ : Constraint n k) (s : Finset (V k × V k)) :
    s ⊆ close ϕ s ∧ expand ϕ (close ϕ s) ⊆ close ϕ s ∧
    ((∀ p ∈ s, Derives ϕ p.1 p.2) → ∀ p ∈ close ϕ s, Derives ϕ p.1 p.2) := by
  fun_induction close ϕ s with
  | case1 s hs => exact ⟨Finset.Subset.refl _, hs, fun h => h⟩
  | case2 s _ ih =>
    exact ⟨Finset.Subset.trans Finset.subset_union_left ih.1, ih.2.1,
      fun hs => ih.2.2 (expand_sound ϕ s hs)⟩

end Closure

/-- The finite closure of the constraint's variable inequalities. -/
def derivedPairs (ϕ : Constraint n k) : Finset (V k × V k) := Closure.close ϕ ∅

theorem mem_derivedPairs (ϕ : Constraint n k) (x y : V k) :
    (x, y) ∈ derivedPairs ϕ ↔ Derives ϕ x y := by
  have spec := Closure.close_spec ϕ ∅
  constructor
  · exact spec.2.2 (by simp) (x, y)
  · intro h
    induction h with
    | refl x =>
      exact spec.2.1 ((Closure.mem_expand ..).mpr (Or.inr (Or.inl rfl)))
    | trans _ _ ih₁ ih₂ =>
      exact spec.2.1 ((Closure.mem_expand ..).mpr
        (Or.inr (Or.inr (Or.inl ⟨_, ih₁, ih₂⟩))))
    | decomp i hl _ hu ih =>
      exact spec.2.1 ((Closure.mem_expand ..).mpr
        (Or.inr (Or.inr (Or.inr ⟨_, _, _, _, i, hl, ih, hu, rfl, rfl⟩))))

/-- The Boolean test for membership in the computed closure. -/
def derivesB (ϕ : Constraint n k) (x y : V k) : Bool :=
  decide ((x, y) ∈ derivedPairs ϕ)

/-- The Boolean closure test decides the generated variable relation. -/
theorem derivesB_iff (ϕ : Constraint n k) (x y : V k) :
    derivesB ϕ x y = true ↔ Derives ϕ x y := by
  simp only [derivesB, decide_eq_true_eq, mem_derivedPairs]

theorem lowerF_iff_lits (ϕ : Constraint n k) (x : V k) :
    LowerF ϕ x ↔ ∃ l ∈ lowerLits ϕ, Derives ϕ l.2 x := by
  constructor
  · rintro ⟨a, u, hl, hd⟩
    exact ⟨(a, u), (mem_lowerLits ϕ a u).mpr hl, hd⟩
  · rintro ⟨⟨a, u⟩, hl, hd⟩
    exact ⟨a, u, (mem_lowerLits ϕ a u).mp hl, hd⟩

theorem upperF_iff_lits (ϕ : Constraint n k) (x : V k) :
    UpperF ϕ x ↔ ∃ m ∈ upperLits ϕ, Derives ϕ x m.1 := by
  constructor
  · rintro ⟨v, b, hu, hd⟩
    exact ⟨(v, b), (mem_upperLits ϕ v b).mpr hu, hd⟩
  · rintro ⟨⟨v, b⟩, hu, hd⟩
    exact ⟨v, b, (mem_upperLits ϕ v b).mp hu, hd⟩

theorem lowerTop_iff_vars (ϕ : Constraint n k) (x : V k) :
    LowerTop ϕ x ↔ ∃ u ∈ topVars ϕ, Derives ϕ u x := by
  simp only [LowerTop, mem_topVars]

theorem upperBot_iff_vars (ϕ : Constraint n k) (x : V k) :
    UpperBot ϕ x ↔ ∃ v ∈ botVars ϕ, Derives ϕ x v := by
  simp only [UpperBot, mem_botVars]

/-- Compute the closure once and search for the three incompatible bound pairs. -/
def labelClashB (ϕ : Constraint n k) : Bool :=
  let s := derivedPairs ϕ
  let lowerF := fun x => ∃ l ∈ lowerLits ϕ, (l.2, x) ∈ s
  let lowerTop := fun x => ∃ u ∈ topVars ϕ, (u, x) ∈ s
  let upperF := fun x => ∃ m ∈ upperLits ϕ, (x, m.1) ∈ s
  let upperBot := fun x => ∃ v ∈ botVars ϕ, (x, v) ∈ s
  decide (∃ x, (lowerTop x ∧ upperBot x) ∨
    (lowerTop x ∧ upperF x) ∨ (lowerF x ∧ upperBot x))

/-- The Boolean clash test decides whether incompatible labels are forced. -/
theorem labelClashB_iff (ϕ : Constraint n k) : labelClashB ϕ = true ↔ LabelClash ϕ := by
  simp only [labelClashB, decide_eq_true_eq, mem_derivedPairs, LabelClash,
    lowerF_iff_lits, lowerTop_iff_vars, upperF_iff_lits, upperBot_iff_vars]

end DeciNSSE
