import Mathlib.Data.Fintype.Prod
import DeciNSSE.Constraints.Basic

/-! # Closure of variable inequalities

Reflexivity, transitivity and decomposition generate variable inequalities.
Finite saturation computes this relation, and incompatible lower and upper
labels give the obstruction to unrestricted satisfiability.
-/

namespace DeciNSSE

variable {k : ℕ}

/-- Variable inequalities generated by reflexivity, transitivity and constructor decomposition. -/
inductive Derives (ϕ : Constraint k) : V k → V k → Prop where
  | refl (x : V k) : Derives ϕ x x
  | trans {x y z : V k} : Derives ϕ x y → Derives ϕ y z → Derives ϕ x z
  | decomp_left {z₁ z₂ u v y₁ y₂ : V k} :
      Lit.fLe z₁ z₂ u ∈ ϕ → Derives ϕ u v → Lit.leF v y₁ y₂ ∈ ϕ →
      Derives ϕ z₁ y₁
  | decomp_right {z₁ z₂ u v y₁ y₂ : V k} :
      Lit.fLe z₁ z₂ u ∈ ϕ → Derives ϕ u v → Lit.leF v y₁ y₂ ∈ ϕ →
      Derives ϕ z₂ y₂

/-- Every derived variable inequality holds in every solution. -/
theorem Derives.sound {ϕ : Constraint k} {x y : V k} (h : Derives ϕ x y) :
    ∀ ρ, Sat ρ ϕ → ρ x ≤ ρ y := by
  induction h with
  | refl x => exact fun _ _ => le_rfl
  | trans _ _ ih₁ ih₂ => exact fun ρ hρ => le_trans (ih₁ ρ hρ) (ih₂ ρ hρ)
  | decomp_left hl _ hu ih =>
    intro ρ hρ
    exact (Tree.node_le_node_iff ..).mp
      (le_trans (le_trans (hρ _ hl) (ih ρ hρ)) (hρ _ hu)) |>.1
  | decomp_right hl _ hu ih =>
    intro ρ hρ
    exact (Tree.node_le_node_iff ..).mp
      (le_trans (le_trans (hρ _ hl) (ih ρ hρ)) (hρ _ hu)) |>.2

/-- A constructor lower bound reaches the variable through derived inequalities. -/
def LowerF (ϕ : Constraint k) (x : V k) : Prop :=
  ∃ z₁ z₂ u, Lit.fLe z₁ z₂ u ∈ ϕ ∧ Derives ϕ u x

/-- A top lower bound reaches the variable through derived inequalities. -/
def LowerTop (ϕ : Constraint k) (x : V k) : Prop :=
  ∃ u, Lit.eqTop u ∈ ϕ ∧ Derives ϕ u x

/-- A constructor upper bound is reachable through derived inequalities. -/
def UpperF (ϕ : Constraint k) (x : V k) : Prop :=
  ∃ v y₁ y₂, Lit.leF v y₁ y₂ ∈ ϕ ∧ Derives ϕ x v

/-- A bottom upper bound is reachable through derived inequalities. -/
def UpperBot (ϕ : Constraint k) (x : V k) : Prop :=
  ∃ v, Lit.eqBot v ∈ ϕ ∧ Derives ϕ x v

theorem LowerF.sound {ϕ : Constraint k} {x : V k} {ρ : V k → Tree}
    (h : LowerF ϕ x) (hρ : Sat ρ ϕ) : (ρ x).fn [] ≠ some Sym.bot := by
  obtain ⟨z₁, z₂, u, hl, hd⟩ := h
  intro hx
  have hle := le_trans (hρ _ hl) (hd.sound ρ hρ)
  rw [(Tree.root_eq_bot_iff _).mp hx] at hle
  exact Tree.node_ne_bot _ _ ((Tree.le_bot_iff _).mp hle)

theorem LowerTop.sound {ϕ : Constraint k} {x : V k} {ρ : V k → Tree}
    (h : LowerTop ϕ x) (hρ : Sat ρ ϕ) : ρ x = Tree.top := by
  obtain ⟨u, hl, hd⟩ := h
  have hle := hd.sound ρ hρ
  have hu : ρ u = Tree.top := hρ _ hl
  rw [hu] at hle
  exact (Tree.top_le_iff _).mp hle

theorem UpperF.sound {ϕ : Constraint k} {x : V k} {ρ : V k → Tree}
    (h : UpperF ϕ x) (hρ : Sat ρ ϕ) : (ρ x).fn [] ≠ some Sym.top := by
  obtain ⟨v, y₁, y₂, hu, hd⟩ := h
  intro hx
  have hle := le_trans (hd.sound ρ hρ) (hρ _ hu)
  rw [(Tree.root_eq_top_iff _).mp hx] at hle
  exact Tree.node_ne_top _ _ ((Tree.top_le_iff _).mp hle)

theorem UpperBot.sound {ϕ : Constraint k} {x : V k} {ρ : V k → Tree}
    (h : UpperBot ϕ x) (hρ : Sat ρ ϕ) : ρ x = Tree.bot := by
  obtain ⟨v, hl, hd⟩ := h
  have hle := hd.sound ρ hρ
  have hv : ρ v = Tree.bot := hρ _ hl
  rw [hv] at hle
  exact (Tree.le_bot_iff _).mp hle

/-- A variable has incompatible lower and upper root-label requirements. -/
def LabelClash (ϕ : Constraint k) : Prop :=
  ∃ x, (LowerTop ϕ x ∧ UpperBot ϕ x) ∨
    (LowerTop ϕ x ∧ UpperF ϕ x) ∨ (LowerF ϕ x ∧ UpperBot ϕ x)

/-- Incompatible root-label requirements preclude a tree solution. -/
theorem LabelClash.unsatisfiable {ϕ : Constraint k} (h : LabelClash ϕ) :
    ¬ ∃ ρ, Sat ρ ϕ := by
  rintro ⟨ρ, hρ⟩
  obtain ⟨x, (⟨hl, hu⟩ | ⟨hl, hu⟩ | ⟨hl, hu⟩)⟩ := h
  · exact Tree.top_ne_bot ((hl.sound hρ).symm.trans (hu.sound hρ))
  · exact hu.sound hρ (by rw [hl.sound hρ]; rfl)
  · exact hl.sound hρ (by rw [hu.sound hρ]; rfl)

namespace Closure

/-- One finite saturation step adding reflexive, transitive and decomposed pairs. -/
def expand (ϕ : Constraint k) (s : Finset (V k × V k)) : Finset (V k × V k) :=
  s ∪ Finset.univ.filter (fun p =>
    p.1 = p.2 ∨
    (∃ z, (p.1, z) ∈ s ∧ (z, p.2) ∈ s) ∨
    (∃ z₂ u v y₂, Lit.fLe p.1 z₂ u ∈ ϕ ∧ (u, v) ∈ s ∧ Lit.leF v p.2 y₂ ∈ ϕ) ∨
    (∃ z₁ u v y₁, Lit.fLe z₁ p.1 u ∈ ϕ ∧ (u, v) ∈ s ∧ Lit.leF v y₁ p.2 ∈ ϕ))

theorem mem_expand (ϕ : Constraint k) (s : Finset (V k × V k)) (x y : V k) :
    (x, y) ∈ expand ϕ s ↔
      (x, y) ∈ s ∨ x = y ∨
      (∃ z, (x, z) ∈ s ∧ (z, y) ∈ s) ∨
      (∃ z₂ u v y₂, Lit.fLe x z₂ u ∈ ϕ ∧ (u, v) ∈ s ∧ Lit.leF v y y₂ ∈ ϕ) ∨
      (∃ z₁ u v y₁, Lit.fLe z₁ x u ∈ ϕ ∧ (u, v) ∈ s ∧ Lit.leF v y₁ y ∈ ϕ) := by
  simp [expand]

theorem expand_sound (ϕ : Constraint k) (s : Finset (V k × V k))
    (hs : ∀ p ∈ s, Derives ϕ p.1 p.2) :
    ∀ p ∈ expand ϕ s, Derives ϕ p.1 p.2 := by
  rintro ⟨x, y⟩ hp
  rcases (mem_expand ϕ s x y).mp hp with
    hp | rfl | ⟨z, hxz, hzy⟩ | ⟨z₂, u, v, y₂, hl, huv, hu⟩ |
      ⟨z₁, u, v, y₁, hl, huv, hu⟩
  · exact hs _ hp
  · exact Derives.refl x
  · exact Derives.trans (hs (x, z) hxz) (hs (z, y) hzy)
  · exact Derives.decomp_left hl (hs _ huv) hu
  · exact Derives.decomp_right hl (hs _ huv) hu

/-- Iterate saturation until no new variable inequalities are added. -/
def close (ϕ : Constraint k) (s : Finset (V k × V k)) : Finset (V k × V k) :=
  if expand ϕ s ⊆ s then s else close ϕ (expand ϕ s)
termination_by k * k - s.card
decreasing_by
  have hs : s ⊂ expand ϕ s :=
    lt_of_le_not_ge Finset.subset_union_left (by assumption)
  have hlt := Finset.card_lt_card hs
  have hle := Finset.card_le_univ (s := expand ϕ s)
  simp only [Fintype.card_prod, Fintype.card_fin] at hle
  omega

/--
Saturation contains the starting relation, is closed under expansion and preserves soundness.
-/
theorem close_spec (ϕ : Constraint k) (s : Finset (V k × V k)) :
    s ⊆ close ϕ s ∧ expand ϕ (close ϕ s) ⊆ close ϕ s ∧
    ((∀ p ∈ s, Derives ϕ p.1 p.2) → ∀ p ∈ close ϕ s, Derives ϕ p.1 p.2) := by
  fun_induction close ϕ s with
  | case1 s hs => exact ⟨Finset.Subset.refl _, hs, fun h => h⟩
  | case2 s _ ih =>
    exact ⟨Finset.Subset.trans Finset.subset_union_left ih.1, ih.2.1,
      fun hs => ih.2.2 (expand_sound ϕ s hs)⟩

end Closure

/-- The computable finite set of all derived variable inequalities. -/
def derivedPairs (ϕ : Constraint k) : Finset (V k × V k) := Closure.close ϕ ∅

/-- Membership in finite saturation is equivalent to inductive derivability. -/
theorem mem_derivedPairs (ϕ : Constraint k) (x y : V k) :
    (x, y) ∈ derivedPairs ϕ ↔ Derives ϕ x y := by
  have spec := Closure.close_spec ϕ ∅
  constructor
  · exact spec.2.2 (by simp) (x, y)
  · intro h
    induction h with
    | refl x =>
      exact spec.2.1 ((Closure.mem_expand ..).mpr (Or.inr (Or.inl rfl)))
    | trans _ _ ih₁ ih₂ =>
      exact spec.2.1 ((Closure.mem_expand ..).mpr
        (Or.inr (Or.inr (Or.inl ⟨_, ih₁, ih₂⟩))))
    | decomp_left hl _ hu ih =>
      exact spec.2.1 ((Closure.mem_expand ..).mpr
        (Or.inr (Or.inr (Or.inr (Or.inl ⟨_, _, _, _, hl, ih, hu⟩)))))
    | decomp_right hl _ hu ih =>
      exact spec.2.1 ((Closure.mem_expand ..).mpr
        (Or.inr (Or.inr (Or.inr (Or.inr ⟨_, _, _, _, hl, ih, hu⟩)))))

/-- Boolean membership in the saturated relation of variable inequalities. -/
def derivesB (ϕ : Constraint k) (x y : V k) : Bool :=
  decide ((x, y) ∈ derivedPairs ϕ)

/-- The Boolean derivability test agrees with the inductive closure relation. -/
theorem derivesB_iff (ϕ : Constraint k) (x y : V k) :
    derivesB ϕ x y = true ↔ Derives ϕ x y := by
  simp only [derivesB, decide_eq_true_eq, mem_derivedPairs]

/-- Decide whether any variable has incompatible root-label requirements. -/
def labelClashB (ϕ : Constraint k) : Bool :=
  let s := derivedPairs ϕ
  let lowerF := fun x => ∃ z₁ z₂ u, Lit.fLe z₁ z₂ u ∈ ϕ ∧ (u, x) ∈ s
  let lowerTop := fun x => ∃ u, Lit.eqTop u ∈ ϕ ∧ (u, x) ∈ s
  let upperF := fun x => ∃ v y₁ y₂, Lit.leF v y₁ y₂ ∈ ϕ ∧ (x, v) ∈ s
  let upperBot := fun x => ∃ v, Lit.eqBot v ∈ ϕ ∧ (x, v) ∈ s
  decide (∃ x, (lowerTop x ∧ upperBot x) ∨
    (lowerTop x ∧ upperF x) ∨ (lowerF x ∧ upperBot x))

/-- The Boolean clash test agrees with the root-label obstruction. -/
theorem labelClashB_iff (ϕ : Constraint k) : labelClashB ϕ = true ↔ LabelClash ϕ := by
  simp only [labelClashB, decide_eq_true_eq, mem_derivedPairs,
    LabelClash, LowerF, LowerTop, UpperF, UpperBot]

end DeciNSSE
